/**
 * Created by joel on 10/20/15.
 */
public class StopWords {

  public static String stopWords = "about\n" +
      "above\n" +
      "across\n" +
      "after\n" +
      "afterwards\n" +
      "again\n" +
      "albeit\n" +
      "all\n" +
      "almost\n" +
      "alone\n" +
      "along\n" +
      "already\n" +
      "also\n" +
      "although\n" +
      "always\n" +
      "among\n" +
      "amongst\n" +
      "an\n" +
      "and\n" +
      "another\n" +
      "any\n" +
      "anyhow\n" +
      "anyone\n" +
      "anything\n" +
      "anywhere\n" +
      "are\n" +
      "around\n" +
      "as\n" +
      "at\n" +
      "b\n" +
      "be\n" +
      "became\n" +
      "because\n" +
      "become\n" +
      "becomes\n" +
      "becoming\n" +
      "been\n" +
      "before\n" +
      "beforehand\n" +
      "behind\n" +
      "being\n" +
      "below\n" +
      "beside\n" +
      "besides\n" +
      "between\n" +
      "beyond\n" +
      "both\n" +
      "but\n" +
      "by\n" +
      "c\n" +
      "can\n" +
      "cannot\n" +
      "co\n" +
      "could\n" +
      "d\n" +
      "down\n" +
      "during\n" +
      "e\n" +
      "each\n" +
      "eg\n" +
      "either\n" +
      "else\n" +
      "elsewhere\n" +
      "enough\n" +
      "etc\n" +
      "even\n" +
      "ever\n" +
      "every\n" +
      "everyone\n" +
      "everything\n" +
      "everywhere\n" +
      "except\n" +
      "f\n" +
      "few\n" +
      "first\n" +
      "for\n" +
      "former\n" +
      "formerly\n" +
      "from\n" +
      "further\n" +
      "g\n" +
      "h\n" +
      "had\n" +
      "has\n" +
      "have\n" +
      "he\n" +
      "hence\n" +
      "her\n" +
      "here\n" +
      "hereafter\n" +
      "hereby\n" +
      "herein\n" +
      "hereupon\n" +
      "hers\n" +
      "herself\n" +
      "him\n" +
      "himself\n" +
      "his\n" +
      "how\n" +
      "however\n" +
      "i\n" +
      "ie\n" +
      "if\n" +
      "in\n" +
      "inc\n" +
      "indeed\n" +
      "into\n" +
      "is\n" +
      "it\n" +
      "its\n" +
      "itself\n" +
      "j\n" +
      "k\n" +
      "l\n" +
      "last\n" +
      "latter\n" +
      "latterly\n" +
      "least\n" +
      "less\n" +
      "ltd\n" +
      "m\n" +
      "many\n" +
      "may\n" +
      "meanwhile\n" +
      "might\n" +
      "more\n" +
      "moreover\n" +
      "most\n" +
      "mostly\n" +
      "much\n" +
      "must\n" +
      "n\n" +
      "namely\n" +
      "neither\n" +
      "never\n" +
      "nevertheless\n" +
      "next\n" +
      "no\n" +
      "nobody\n" +
      "none\n" +
      "noone\n" +
      "nor\n" +
      "not\n" +
      "nothing\n" +
      "now\n" +
      "nowhere\n" +
      "o\n" +
      "of\n" +
      "off\n" +
      "often\n" +
      "on\n" +
      "once\n" +
      "one\n" +
      "only\n" +
      "onto\n" +
      "or\n" +
      "other\n" +
      "others\n" +
      "otherwise\n" +
      "our\n" +
      "ours\n" +
      "ourselves\n" +
      "out\n" +
      "over\n" +
      "own\n" +
      "p\n" +
      "per\n" +
      "perhaps\n" +
      "q\n" +
      "r\n" +
      "rather\n" +
      "s\n" +
      "same\n" +
      "seem\n" +
      "seemed\n" +
      "seeming\n" +
      "seems\n" +
      "several\n" +
      "she\n" +
      "should\n" +
      "since\n" +
      "so\n" +
      "some\n" +
      "somehow\n" +
      "someone\n" +
      "something\n" +
      "sometime\n" +
      "sometimes\n" +
      "somewhere\n" +
      "still\n" +
      "such\n" +
      "t\n" +
      "than\n" +
      "that\n" +
      "the\n" +
      "their\n" +
      "them\n" +
      "themselves\n" +
      "then\n" +
      "thence\n" +
      "there\n" +
      "thereafter\n" +
      "thereby\n" +
      "therefore\n" +
      "therein\n" +
      "thereupon\n" +
      "these\n" +
      "they\n" +
      "this\n" +
      "those\n" +
      "though\n" +
      "through\n" +
      "throughout\n" +
      "thru\n" +
      "thus\n" +
      "together\n" +
      "too\n" +
      "toward\n" +
      "towards\n" +
      "u\n" +
      "under\n" +
      "until\n" +
      "up\n" +
      "upon\n" +
      "v\n" +
      "very\n" +
      "via\n" +
      "w\n" +
      "was\n" +
      "well\n" +
      "were\n" +
      "what\n" +
      "whatever\n" +
      "whatsoever\n" +
      "when\n" +
      "whence\n" +
      "whenever\n" +
      "whensoever\n" +
      "where\n" +
      "whereafter\n" +
      "whereas\n" +
      "whereat\n" +
      "whereby\n" +
      "wherefrom\n" +
      "wherein\n" +
      "whereinto\n" +
      "whereof\n" +
      "whereon\n" +
      "whereto\n" +
      "whereunto\n" +
      "whereupon\n" +
      "wherever\n" +
      "wherewith\n" +
      "whether\n" +
      "which\n" +
      "whichever\n" +
      "whichsoever\n" +
      "while\n" +
      "whilst\n" +
      "whither\n" +
      "who\n" +
      "whoever\n" +
      "whole\n" +
      "why\n" +
      "will\n" +
      "with\n" +
      "within\n" +
      "without\n" +
      "would\n" +
      "x\n" +
      "yet\n" +
      "z";

}
